### ISSUE TITLE
trying to start gui on matlab 2020 

### ISSUE THREAD

**Issue by tonynakhla13** [amburosesekar/WSNsimulatorMatlab#1]
the gui on 2020 doesn't work it always saying in the routing function 
Index exceeds the number of array elements (0).

Error in WSNToolbox>pushbutton3_Callback (line 465)
          dist2Leach=pdist2([Xb;Yb]',[X(ind);Y(ind)]');
can you help me please

**Comment by amburosesekar** [comment]
I think you don't have a statistical toolbox in matlab. pdist2 inside
statistical toolbox

**Comment by tonynakhla13** [comment]
i think i have one 
also the problem happen before 
Index exceeds the number of array elements (0).

Error in WSNToolbox>pushbutton3_Callback (line 461)
       ind=A1(3);
![image](https://user-images.githubusercontent.com/51010726/127435409-089b4af3-b240-4a86-a12e-5cb48d5a4b28.png)

**Comment by amburosesekar** [comment]
Ok, I'll check it out.

**Comment by amburosesekar** [comment]
kindly test at-first maintest.m in GitHub code, then we ll move on GUI

**Comment by tonynakhla13** [comment]
hi 
i tried the maintest.m it works fines no problem here

**Comment by amburosesekar** [comment]
okay, thanks for letting me know, I used Matlab2015b version for GUI design, soon I will update **App Designer instead of GUI** :)
